name: Deploy to shinyapps.io

on:
  push:
    branches:
      - CI-deployment # Adjust this as needed for your workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.13" # Use a supported Python version

      - name: Install rsconnect-python
        run: pip install rsconnect-python

      - name: Configure rsconnect-python
        env:
          TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: rsconnect add --account gallery --name gallery --token $TOKEN --secret $SECRET

      - name: Deploy app to shinyapps.io
        run: rsconnect deploy shiny /basicapp --name gallery --title "Basic app"
