name: Deploy to shinyapps.io

on:
  push:
    branches:
      - CI-deployment # Adjust this as needed for your workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-dir: ["basic-app", "dashboard"] # List your app directories here
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.13"
      - name: Install rsconnect-python
        run: pip install rsconnect-python
      - name: Configure rsconnect-python
        env:
          TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: rsconnect add --account gallery --name gallery --token $TOKEN --secret $SECRET
      - name: Deploy app to shinyapps.io
        run: rsconnect deploy shiny ./${{ matrix.app-dir }} --name gallery --title ${{ matrix.app-dir }} --entrypoint app-core.py
